### ISSUE TITLE
Expose reporter(s) & reportDir via package.json config?

### ISSUE THREAD

**Issue by jameswomack** [bcoe/nyc#156]
I'm interested in moving `--reportDir=tests/output/coverage --reporter=html` into the package.json "nyc" config object, but don't know if that's something anyone else would see as being valuable.

**Comment by bcoe** [comment]
@jameswomack sounds like a great configuration option, no objection here :+1:

**Comment by jamestalmage** [comment]
For that matter, there should be 100% config parity between the CLI and the `package.json` config.

CLI should take priority, defaulting to the config (which in turn defaults to our set of "sensible" defaults).

**Comment by jameswomack** [comment]
@jamestalmage That's what seems intuitive to me

**Comment by bcoe** [comment]
`yargs@4.x` is slowly plodding along, this almost feels like something that could be handled by yargs eventually.

I like that both `ava` and `yargs` have moved towards using a prefix in the package.json for their config -- one could imagine a world where someone indicates that yargs should automatically parse this stanza and use it to override default settings.

**Comment by bcoe** [comment]
... perhaps we could add this on the yargs `4.x` branch, and I could start publishing a `4.x` tag of yargs to npm?

**Comment by jamestalmage** [comment]
> perhaps we could add this on the yargs 4.x branch

:+1: The only contentious discussion we had w/ regard to this behavior in AVA, was what to do with array based args (i.e. `ava --require babel/register --require some-other-module`). What do you do to the `require` array in `package.json` if a `--require` option is used?

 My contention was that you blow the original array away, forcing them to rewrite all the `--require` tags if that is what they want (this is what we ended up doing). 

The other suggestion was that we append to the existing array. I argued against this because there's no good way to remove items from the default array.

I think our decisions make sense for a `--require` and `--reporter` flags. I guess it's possible there's some option out there where appending would be desired. I'm not coming up with one though.

**Comment by sindresorhus** [comment]
> For that matter, there should be 100% config parity between the CLI and the package.json config.
> CLI should take priority, defaulting to the config (which in turn defaults to our set of "sensible" defaults).

:+1: That's been working very well for AVA and XO.

> I think our decisions make sense for a --require and --reporter flags.

I too feel we made the right choice with that.

**Comment by lloydcotten** [comment]
Just a note that any implementation done for these options, should also be done for the new --extension arg / config setting that is now implemented in pull request #163.

**Comment by jeffijoe** [comment]
It seems this does not work for the  `--reporter` option - the values in `package.json` always seem to win for me?
