### ISSUE TITLE
Should .nyc_output be deleted?

### ISSUE THREAD

**Issue by sarbbottam** [bcoe/nyc#197]
Since `.nyc_output` is a temp directory, I am wondering if `nyc` should delete it, once the process ends.

**Comment by jamestalmage** [comment]
We allow `nyc report` commands to be run at a later time, and `.nyc_output` still needs to be around for that.

**Comment by sarbbottam** [comment]
Wondering if it would be possible to run `nyc report` on `coverage` dir. Please excuse my ignorance. Thanks!

**Comment by jamestalmage** [comment]
`nyc report` operates basically the same as `istanbul report`, except it first combines all the contents of `.nyc_output` before running the report. Running `.nyc_output` on the coverage directory wouldn't make a lot of sense (you already have `istanbul report` for that)

**Comment by bcoe** [comment]
Hey @sarbbottam, as @jamestalmage says the reason for not deleting `.nyc_output` on each run is that it can be handy to output reports multiple times:

`nyc npm test`.
`nyc report lcov-text`
`nyc report lcov`

If you want to cleanup after nyc, I recommend adding a `posttest` command that uses `rimraf` to nuke the folder :+1:

**Comment by andyhu** [comment]
Shall we provide an option to not generate .nyc_output at all?

**Comment by jamestalmage** [comment]
Not possible. We need it to store coverage info

**Comment by mmc41** [comment]
Would it be possible to configure where to store the coverage info ? F.x. in the same folder as the reports ?

**Comment by vamonke** [comment]
You can specify where .nyc_output is generated under `temp-directory` in the config. e.g.
```
"nyc": {
  "temp-directory": "./coverage/.nyc_output"
}
```

source: https://github.com/istanbuljs/nyc/blob/master/index.js#L43

**Comment by ozzyogkush** [comment]
The "temp-directory" option is not documented in the repository README.

**Comment by aalexgabi** [comment]
I'm not a fan of creating a directory under my project in general and especially when I specify explicitly --report-dir. This should be an option and not the default behavior. For me nyc should use a tmp directory by default generated by something like `mktemp -d` and the equivalent on Windows.

The problem here is the assumption that there will be only one instance of the covered process running at a given path. I wonder how nyc handles this case but I suppose that there are concurrency issues with this approach.

In my case I launch two instances of the same service under nyc and then I launch the integration tests as a separate process. At the end I use istanbul-combine to combine the two coverage reports into one and I use nyc check-coverage for the combined coverage.

In general I feel that nyc is the only option for the NodeJS community and it's quality is questionable compared to istanbul and in general. I started using it for a week and I already stumbled on a couple of bugs, undocumented features in the man page, strange imposed defaults like the number of lines at 90% when running nyc check-coverage, uncovered js files without extension etc.

I know this is an open source and anybody is welcome to contribute but I'm still disappointed that such a large community does not have what I would call "proper tools".

**Comment by IsFlwrs** [comment]
I have resolved it adding the `.nyc_output` folder under the node_modules.
All the `node_modules` is ignored by the `.gitignore` file.


```
"nyc": {
  "temp-directory": "./node_modules/coverage/.nyc_output"
}
```

**Comment by timbeadle** [comment]
> I have resolved it moving the .nyc_output folder under the node_modules.

@IsFlwrs This isn't a very good idea. `node_modules` contains your dependencies, which you may wish to remove and reinstall at any time.

It's better to add `.nyc_output` to your `.gitignore` file.
