### ISSUE TITLE
Why the package name is `nyc`

### ISSUE THREAD

**Issue by sarbbottam** [bcoe/nyc#208]
Wondering if it's an abbreviation, what does `nyc` mean?

**Comment by novemberborn** [comment]
I imagine it stands for New York City, just like the Istanbul code coverage tool is named after the Turkish city.

**Comment by jamestalmage** [comment]
https://youtu.be/fIBRw0dSu34

**Comment by jamestalmage** [comment]
Closing as this is nobody's business but the Turks.

**Comment by jeffijoe** [comment]
@novemberborn that's what I am thinking, too - but **Nail Your Coverage** could work, too.

**Comment by viztastic** [comment]
'Now You're Covered'

**Comment by kushalmahajan** [comment]
What's the official answer then? Just curious! 
Random or something related to history?

**Comment by bcoe** [comment]
@kushalmahajan nyc was designed to be a tool that extended on the functionality of Istanbul; introducing support for subprocesses, and a zero-configuration approach to coverage. I called it nyc for two reasons:

1. as a joke, because in the They Might Be Giants song Istanbul Not Constantinople, they mention Istanbul, Constantinople, new Amsterdam, and New York City inn conjunction.
2. because I wanted a short name, so that folks could add it to existing test scripts: `mocha` becomes `nyc mocha`.

**Comment by cgm42** [comment]
On that matter, does anyone know why it's called istanbul?

**Comment by sarbbottam** [comment]
> On that matter, does anyone know why it's called istanbul?

@cgm42 https://github.com/gotwarlost/istanbul#why-the-funky-name
