### ISSUE TITLE
build currently failing on master

### ISSUE THREAD

**Issue by bcoe** [bcoe/nyc#95]
All the branches merged were in the green, but it seems as though the combined build is failing on travis:

https://travis-ci.org/bcoe/nyc

**Comment by jamestalmage** [comment]
Digging into it now

**Comment by bcoe** [comment]
Cool, in the meantime, working on getting AppVeyor up and running for builds too :+1:

**Comment by jamestalmage** [comment]
Well, at least part of the reason is that I am an idiot.

I was using the old name and api `capture-require` vs, the new one `append-transform`. I'm not sure why that would make it fail on Travis though.

Also, I had `capture-require` installed as a `dev-dependency`. So that would certainly have caused problems (but not on travis I wouldn't think).

**Comment by bcoe** [comment]
@jamestalmage that probably explains both problems -- it's been a busy few weeks for me, and I honestly just thought I'd dreamt the whole renaming thing ;)

**Comment by jamestalmage** [comment]
Well,
Turns out it was me being an idiot, plus the presence of the Coveralls environment variable on Travis.
Apparently that forces tap into coverage mode, which meant we were double wrapping ourselves again, a `--no-cov` flag seems to have fixed it.

**Comment by bcoe** [comment]
@jamestalmage I won't have you disparaging yourself! especially right before I'm going to try to convince you to get our tests running on Windows :stuck_out_tongue: 

the `nyc` - `travis` - `tap` - `nyc` - `sourcemap`, etc., interaction is confusing.
